[package]
name = "nanite"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.7.0", features = [
    "defmt",
    "arch-cortex-m",
    "executor-thread",
] }
embassy-time = { version = "0.4.0", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }
embassy-rp = { version = "0.4.0", features = [
    "defmt",
    "unstable-pac",
    "critical-section-impl",
    "time-driver",
    "intrinsics",
    "rom-v2-intrinsics",
    "rp235xa",
    "binary-info",
] }
embassy-futures = "0.1.0"
defmt = { version = "0.3", features = ["encoding-raw"] }
rbq = { path = "../rbq" }
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
critical-section = "1.1.0"

[package.metadata.cargo-machete]
ignored = []
