cargo-features = ["per-package-target"]

[package]
name = "nanite"
version = "0.1.0"
edition = "2024"
default-target = "thumbv8m.main-none-eabihf"

[dependencies]
cortex-m = "0.7.6"
cortex-m-rt = { version = "0.7.0", features = ["device"] }
embedded-hal = "1.0.0"
rp235x-hal = { git = "https://github.com/rp-rs/rp-hal", version = "0.3.0", features = [
    "binary-info",
    "critical-section-impl",
    "rt",
    "defmt",
] }
panic-halt = "0.2.0"
rp-binary-info = "0.1.0"

[package.metadata.cargo-machete]
ignored = ["cortex-m", "cortex-m-rt", "rp-binary-info"]
