cargo-features = ["per-package-target"]

[package]
name = "nanite"
version = "0.1.0"
edition = "2024"
default-target = "thumbv8m.main-none-eabihf"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = { version = "0.7.5", features = ["device"] }
embedded-hal = "1.0.0"
rp235x-hal = { version = "0.3.0", features = [
    "binary-info",
    "critical-section-impl",
    "rt",
    "defmt",
] }
rp-binary-info = "0.1.1"

[package.metadata.cargo-machete]
ignored = ["cortex-m", "cortex-m-rt", "rp-binary-info"]
