name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly-2025-02-14 --profile default
          rustup target add thumbv8m.main-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - name: Run `cargo check`
        run: cargo check --profile ci --locked --workspace --all-features

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly-2025-02-14 --profile default
          rustup target add thumbv8m.main-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - name: Run `cargo clippy`
        run: cargo clippy --profile ci --locked --workspace --all-features -- -D warnings

  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly-2025-02-14 --profile default
          rustup target add thumbv8m.main-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - name: Run `cargo fmt`
        run: cargo fmt --all --check

  test-portable:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly-2025-02-14 --profile default
          rustup target add thumbv8m.main-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - name: Run `cargo test`
        run: cargo test --profile ci --locked --workspace --exclude nanite --all-features

  tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly-2025-02-14 --profile default
          rustup target add thumbv8m.main-none-eabihf
      - uses: Swatinem/rust-cache@v2
      - name: Install tools
        run: |
          cargo install --config .cargo/config.toml --profile ci --locked --version "=0.8.0" cargo-machete
      - name: Run `cargo machete`
        run: cargo machete
