name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ~/.rustup
          key: toolchain-${{ hashFiles('rust-toolchain.toml') }}
      - name: Install toolchain
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          cargo version
          rustup target add thumbv8m.main-none-eabihf
      - name: Run `cargo check`
        run: cargo check --profile ci --locked --workspace --all-features

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ~/.rustup
          key: toolchain-${{ hashFiles('rust-toolchain.toml') }}
      - name: Install toolchain
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          cargo version
          rustup target add thumbv8m.main-none-eabihf
      - name: Run `cargo clippy`
        run: cargo clippy --profile ci --locked --workspace --all-features -- -D warnings

  test-portable:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ~/.rustup
          key: toolchain-${{ hashFiles('rust-toolchain.toml') }}
      - name: Install toolchain
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          cargo version
          rustup target add thumbv8m.main-none-eabihf
      - name: Run `cargo test`
        run: cargo test --profile ci --locked --workspace --exclude nanite --all-features

  tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ~/.rustup
          key: toolchain-${{ hashFiles('rust-toolchain.toml') }}
      - name: Install toolchain
        if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
        run: |
          cargo version
          rustup target add thumbv8m.main-none-eabihf
      - name: Install tools
        run: |
          cargo install --config .cargo/config.toml --profile ci --locked --version "=0.8.0" cargo-machete
      - name: Run `cargo fmt`
        run: cargo fmt --all --check
      - name: Run `cargo machete`
        run: cargo machete
